apiVersion: v1
kind: Service
metadata:
  name: k8s-app-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 3000
  selector:
    app: k8s-app